title: Connect a Raspberry Pi Camera Module
hero_image: images/banner.png
description: Learn how to connect the Raspberry Pi Camera Module
original_url:
theme: cc-prototype
listed: false
ingredient: true
copyedit: true
interests: 
technologies: "picamera, raspberry pi"
steps:
  - title: Attach the camera
