title: rpi-connect-camera
hero_image: images/banner.png
subtitle: rpi-connect-camera subtitle
description: rpi-connect-camera description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
